name: Deploy to Firebase Hosting on Merge
on:
  push:
    branches:
      - main
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: |
          export CI=false  # Set CI environment variable to false to prevent treating warnings as errors
          npm run build
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ADOTESEUPETCURITIBA }}
          projectId: adoteseupetcuritiba
